### ISSUE TITLE
Reopening: Cannot install PyQt5 under Python 2.7.14

### ISSUE THREAD

**Issue by sfsdfd** [zopefoundation/ZEO#101]
This issue is a reopening of https://github.com/zopefoundation/ZEO/issues/77.

My version of python in /usr/local/bin is 2.7.14:84471935ed, Sept 16, 2017.

Calling ./python -m pip install python-qt5 produces this error:

No files/directories in /private/var/folders/cm/60_4h2mj23d_70fhqwvtjf7m0000gn/T/pip-build-MyNknQ/python-qt5/pip-egg-info (from PKG-INFO)

Looks like we're dead in the water until this issue is acknowledged and properly addressed.

**Comment by jamadden** [comment]
What does this problem have to do with ZEO? ZEO is not PyQt5 and has nothing to do with PyQt5 AFAIK. Wouldn't this be better addressed to the [maintainers of PyQt5](https://www.riverbankcomputing.com/support/help)?

**Comment by tseaver** [comment]
Agreed:  this is either an issue witth PyQt5's own packaging, or an out-of-date setuptools / pip version.

```bash
$ /opt/Python-2.7.14/bin/virtualenv /tmp/zeo-101
New python executable in /tmp/zeo-101/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/zeo-101/bin/pip install -U setuptools pip
Requirement already up-to-date: setuptools in /tmp/zeo-101/lib/python2.7/site-packages
Requirement already up-to-date: pip in /tmp/zeo-101/lib/python2.7/site-packages
$ /tmp/zeo-101/bin/pip install python-qt5
Collecting python-qt5
  Downloading python-qt5-0.1.10.zip (57.5MB)
    100% |████████████████████████████████| 57.5MB 32kB/s 
No files/directories in /tmp/pip-build-RXho_j/python-qt5/pip-egg-info (from PKG-INFO)
```

So, looks like it is PyQt5.
