### ISSUE TITLE
ZEO ClientStorage wait_timeout is ignored on Windows

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/ZEO#106]
I was writing unit tests for zodbbrowser when I noticed that under Windows the following code never times out:

```python
from ZEO.ClientStorage import ClientStorage
storage = ClientStorage('/no/such/zeo/socket', wait_timeout=0.001, strorage='1', read_only=True)
```

Instead it hangs forever (I killed the hung Jenkins job after 19 hours).

The timeout works fine on Linux.

**Comment by tseaver** [comment]
On windows, shouldn't that just raise immediately?  There is no support for sockets-on-the-filesystem in Windows, AFAIK.

**Comment by mgedmin** [comment]
> On windows, shouldn't that just raise immediately? There is no support for sockets-on-the-filesystem in Windows, AFAIK.

That is a very good point!  But it doesn't raise, [it hangs](https://ci.appveyor.com/project/mgedmin/zodbbrowser/build/build-85-master).

If you want a reproducible example,

    git clone https://github.com/mgedmin/zodbbrowser
    git checkout 8917ecb 
    tox -e py27
