### ISSUE TITLE
Update to msgpack >= 0.6

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZEO#122]
In #115 the dependencies have been updated from the deprecated `msgpack-python` to 		     `msgpack < 0.6` as there are test failures with newer versions.

It would be good to fix the test failures to be able to use the most recent version.

**Comment by jmuchemb** [comment]
Fixed by 503dccb1de91e0073cbdfa8e68ef36d9cd556c82.

**Comment by icemac** [comment]
Cool, thank you!
