### ISSUE TITLE
First read not consistent after write from other thread

### ISSUE THREAD

**Issue by benoitguigal** [zopefoundation/ZEO#13]
I have two threads connecting to a ZODB via ZEO. 
Thread A is reading data and thread B is writing data periodically.
The issue I am facing is that first read from A after a write from B is not consistent. Only after that first read does A see the updated objects. I guess this is somehow related to caching but I am not quite sure.
Can you provide me with some guidance ?

**Comment by jimfulton** [comment]
Thread A won't see changes after the start of a transaction, so to see changes from B, it needs to commit or abort the current transaction.

**Comment by benoitguigal** [comment]
I forgot to mention it is after B commit the transaction

**Comment by jimfulton** [comment]
Thread A needs to commit or abort to see new changes.

**Comment by benoitguigal** [comment]
Indeed that fixed it, thanks
