### ISSUE TITLE
fshelper.checkSecure deprecation warning

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/ZEO#134]
When setting a blob directory, the following warning appears:
```python
...ZEO/ClientStorage.py:252: DeprecationWarning: checkSecure is deprecated. Permissions are no longer set by ZODB
    self.fshelper.checkSecure()
```
My company has thousands of unit tests, and a lot of them are generating this warning in test reports. This makes other warnings hard to read.

**Comment by jamadden** [comment]
That was a behaviour change [in ZODB 5.2.2](https://github.com/zopefoundation/ZODB/blob/master/CHANGES.rst#522-2017-04-11). From that version on, `checkSecure` issues a warning. Before that, if filesystem permissions weren't set as expected, it would call `log`, which wound up invoking a `logger.log`.

ZEO's setup.py only depend on ZODB 5.1, so we can't assume that ZODB 5.2.2+ is in use.

However, ZEO *does* directly instantiate the concrete class that produces the warning (or log message, for old versions). 

I think we can simply remove the call to `checkSecure`, no matter what version of ZODB we're using. The warning or log message is only a side-effect. Unless a user is on ZODB < 5.2.2, *and* has monkey-patched either `checkSecure` itself, or the `ZODB.blob` module to replace either the `FilesystemHelper` class or the `log` function, or has some *very* involved logging configuration (all of which seems unlikely), users won't be able to notice a difference programmatically. That seems like a reasonable risk.

In the meantime, configuring `$PYTHONWARNINGS` appropriately could filter this warning out for you.

**Comment by azmeuk** [comment]
Thank you very much!
