### ISSUE TITLE
--configuration option not recognized

### ISSUE THREAD

**Issue by sblondon** [zopefoundation/ZEO#138]
`-C` option works but not `--configuration` option:

```
$ ./venv/bin/runzeo -C zeo.config  # ok
$ ./venv/bin/runzeo --configuration zeo.config 
Error: option --configuration not recognized
For help, use ./venv/bin/runzeo -h
```

The documentation says it should be equivalent:
```
$ ./venv/bin/runzeo -h
Start the ZEO storage server.

Usage: ./venv/bin/runzeo [-C URL] [-a ADDRESS] [-f FILENAME] [-h]

Options:
-C/--configuration URL -- configuration file or URL
[snip]
```

It's because the options are parsed by the `zdaemon.zeoptions.ZDOptions()` class, which use `--configure` as long parameter to get the configuration file. So there is a difference:
```
runzeo.__doc__ : -C/--configuration
zdoptions.ZDOoptions.__doc__ : -C/--configure
```

`ZDOoptions` documentation fits to its own code, line 73:
``` python
self.add("configfile", None, "C:", "configure=")
```

It's not possible to just add
``` python
self.add("configfile", None, "C:", "configuration=")
```
in `runzeo.py:ZEOOptionsMixin.add_zeo_options()` because the same `-C` option is still used by `ZDOptions`.

Perhaps it would be better to change one of the long option of runzeo.py or `ZDOptions` class to provide the same long parameter name in both packages?
Cons:
 - breaks the previous compatibility

Pros:
 - improve the homogeneity, so easier to use
 - probably does not break to much because no one can use it currently.

I'm ok to make a PR but I prefer to get feedbacks before.

Tested with package ZEO-5.2.1, python 3.7.

**Comment by sblondon** [comment]
So `--configure` option works:

```
./venv/bin/runzeo --configure zeo.config
```

**Comment by icemac** [comment]
+1 to use `--configure` all over the place.
