### ISSUE TITLE
Long connection time

### ISSUE THREAD

**Issue by benoitguigal** [zopefoundation/ZEO#14]
I am experiencing an issue where it takes up to two minutes for the clients to set up a first connection (see below). Is is related to the time re-building the cache ? Note that my client and server are running on the same host.
```
04.01.16 07:55:06 [+0100] INFO:ZEO.ClientStorage:/var/run/zeo.sock ClientStorage (pid=60) created RW/normal for storage: '1'
04.01.16 07:55:06 [+0100] INFO:ZEO.cache:created temporary cache file '<fdopen>'
04.01.16 07:55:07 [+0100] WARNING:ZEO.zrpc:(60) CW: error connecting to /var/run/zeo.sock: ENOENT
04.01.16 07:55:08 [+0100] WARNING:ZEO.zrpc:(60) CW: error connecting to /var/run/zeo.sock: ENOENT
04.01.16 07:55:10 [+0100] WARNING:ZEO.zrpc:(60) CW: error connecting to /var/run/zeo.sock: ENOENT
04.01.16 07:55:14 [+0100] WARNING:ZEO.zrpc:(60) CW: error connecting to /var/run/zeo.sock: ENOENT
04.01.16 07:55:22 [+0100] WARNING:ZEO.zrpc:(60) CW: error connecting to /var/run/zeo.sock: ENOENT
04.01.16 07:55:38 [+0100] WARNING:ZEO.zrpc:(60) CW: error connecting to /var/run/zeo.sock: ENOENT
04.01.16 07:56:08 [+0100] INFO:ZEO.ClientStorage:/var/run/zeo.sock Testing connection <ManagedClientConnection /var/run/zeo.sock>
04.01.16 07:56:08 [+0100] INFO:ZEO.zrpc.Connection('C'):(/var/run/zeo.sock) received handshake 'Z3101'
04.01.16 07:56:08 [+0100] INFO:ZEO.ClientStorage:/var/run/zeo.sock Server authentication protocol None
04.01.16 07:56:08 [+0100] INFO:ZEO.ClientStorage:/var/run/zeo.sock Connected to storage: /var/run/zeo.sock
04.01.16 07:56:08 [+0100] INFO:ZEO.ClientStorage:/var/run/zeo.sock No verification necessary -- empty cache
```

**Comment by tseaver** [comment]
Can you look at the log from the server?  It appears that its Unix-domain socket does not exist when the client tries to connect.

One possible explanation would be that the ZEO server was not shut down cleanly, and is therefore taking time to rebuild the index for its Filestorage.

**Comment by benoitguigal** [comment]
Log on the servers look like this.
```
------                                                                                                                  
2016-01-04T07:54:53 INFO ZEO.runzeo (59) opening storage '1' using FileStorage                                          
------                                                                                                                  
2016-01-04T07:55:44 INFO ZEO.StorageServer StorageServer created RW with storage                                        
s: 1:RW:/data/db.fs                                                                                                     
------                                                                                                                  
2016-01-04T07:55:44 INFO ZEO.zrpc (59) listening on /var/run/zeo.sock 
```
I just realized my database grew a lot in size (2GB) beacause I was not doing regular pack. Can it be related ?

**Comment by mgedmin** [comment]
The log says that ZEO takes 51 seconds to open the FileStorage, which is a sure sign it's rebuilding the index.  The client is doing retries with exponential backoff in the mean time.  This can get fun, when the ZODB grows to 20 GB and the exponential delay reaches tens of minutes.

So, yes, things are working as designed here.  Unless you shut down your ZEO server cleanly and it failed to write an up-to-date Data.fs.index file, in which case please file a bug and tell us how to reproduce that.

**Comment by jimfulton** [comment]
FTR, the exponential back-off has an upper limit. This is configurable and defaults to 5 minutes. (I think I tried to reduce this to 30 seconds, but didn't change it in the right place. :( )  Future ZEO versions will get rid of the exponential back-off, which is silly in this situation.
