### ISSUE TITLE
Improve log and exception message

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/ZEO#142]
When there is a newer transaction id on the client than on the server - for instance after a backup has been restored - following message gets logged:
"ClientStorageError: Client has seen newer transactions than server!"

The admin is left with this message and probably does not know how to recover a working state - as Zope is no longer usable.

What worked for me - and maybe is not always the best solution was to remove the zec file, cf 
https://docs.plone.org/3/en/manage/troubleshooting/transactions.html#zeostorage-client-has-seen-newer-transactions-than-server

There may be other reasons for this error and maybe other recovery steps make more sense then.

From a quick glance tox is not setup to run coverage (see #123 ), and from looking at the code and the tests it seems the branch ("Cache newer than server") is untested.

**Update**
The branch gets covered by 
https://github.com/zopefoundation/ZEO/blob/a6c1ffcefda76354b07e56af463d5da8e90cf60c/src/ZEO/asyncio/tests.py#L437
Was hard to spot, as the test does neither check for the AssertionError nor for the log message.

https://github.com/zopefoundation/ZEO/blob/bd7cd066a49d7090263211574aa0a0a38010cd65/src/ZEO/asyncio/client.py#L488-L493

Also, the tests for ZEO seems to be quite flaky, cf #140 

@jamadden made some good suggestions how to proceed:
https://github.com/zopefoundation/ZEO/pull/139#discussion_r278190611

[Removed wrong assumption about assert / AssertionError]

**Comment by jamadden** [comment]
> I do not know what to think about the AssertionError - as there is no guarantee that it get raised,

It will always be raised. Only the `assert` statement can be disabled by `-O`; a `raise` is always executed.

**Comment by jugmac00** [comment]
the test failure is unrelated and already reported as #179
