### ISSUE TITLE
DeprecationWarning: encoding is deprecated, Use raw=False instead.

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/ZEO#143]
`/home/jugmac00/Projects/ZEO/.tox/coverage/lib/python2.7/site-packages/ZEO/asyncio/marshal.py:69: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  return unpackb(data, encoding='utf-8', use_list=False)
`

**Comment by jmuchemb** [comment]
Fixed by 503dccb1de91e0073cbdfa8e68ef36d9cd556c82.
