### ISSUE TITLE
Server leaks file descriptors of blob tempfiles on error

### ISSUE THREAD

**Issue by wosc** [zopefoundation/ZEO#149]
If the assertion in [storeBlobStart](https://github.com/zopefoundation/ZEO/blob/master/src/ZEO/StorageServer.py#L460) fails, the client aborts, `storeBlobEnd` is never called, and the file handle `self.blob_tempfile[0]` is never closed.

We've seen this in production, where a cronjob triggers this exception (for reasons yet unknown), and the server then ran out of file descriptors after a few days.

I guess something like this would be safer:
```python
    def storeBlobStart(self):
        if self.blob_tempfile is not None:
            os.close(self.blob_tempfile[0])
            raise AssertionError('%s is already open' % self.blob_tempfile[1])
        self.blob_tempfile = tempfile.mkstemp(
            dir=self.storage.temporaryDirectory())
```

**Comment by mauritsvanrees** [comment]
Can this be closed now that the related issue #150 is fixed in version 5.3.0?
Or is this still an issue?
