### ISSUE TITLE
Client incorrectly interleaves blob calls on large enough blobs

### ISSUE THREAD

**Issue by wosc** [zopefoundation/ZEO#150]
After #149 I of course wanted to know why the mentioned cronjob causes the zeo server to error with "you said blobStart twice" in the first place.

### Bug

The issue I found (after a metric ton of printf debugging) is that [call_async_iter](https://github.com/zopefoundation/ZEO/blob/master/src/ZEO/asyncio/base.py#L141) currently [always directly writes the first message](https://github.com/zopefoundation/ZEO/blob/master/src/ZEO/asyncio/base.py#L81), even when `self.pause` is active at that moment. Which means that the overall ordering of message calls is **not** preserved.

Im my example, the client wants to store two blobs in sequence, and the first one is large enough, so the following can happen:

1. `storeBlob` for the first blob runs `call_async_iter`, which starts writing messages: blobStart, then blobChunk several times. At some point, the flow control kicks in and calls `pause_writing`. `writeit` puts the remaining blobChunk and blobEnd messages into the `self.output` list.
2. If `storeBlob` is now called for the second blob _before_ `resume_writing` comes back in, the second `blobStart` is written immediately -- before the paused blobEnd had a chance to be written.

### Impact 

In general, this means that the order in which messages go out to the server is currently not guaranteed to be the same as they came in to the client. I _guess_ this does not cause more trouble because a) flow control probably only kicks in for blobs and b) only blobs are that sensitive to the order of operations. But this is only a guess, I'm not overly familiar with the ZEO protocol.

### Bugfix

I don't have a proposal, sorry. My first thought was something like this:
```python
def writeit(data):
    data = iter(data)
    if paused:
        append(data)
        return
    for message in data:
        writelines((pack(">I", len(message)), message))
        if paused:
            append(data)
            break
```
but that doesn't fix the problem (I've tried it).

**Comment by wosc** [comment]
Here's a failing test that reproduces the problem:

```python
class BlobTest(CommonSetupTearDown):

    def setUp(self):
        import tempfile
        super(BlobTest, self).setUp()
        self.server_blob_dir = tempfile.mkdtemp()
        self.client_blob_dir = tempfile.mkdtemp()

    def tearDown(self):
        import shutil
        super(BlobTest, self).tearDown()
        shutil.rmtree(self.server_blob_dir)
        shutil.rmtree(self.client_blob_dir)

    def _client_options(self):
        return {'blob_dir': self.client_blob_dir}

    def checkBlobRequestInterleaving(self):
        from ZODB.blob import Blob

        self.shutdownServer()
        self._servers = []
        self.startServer(blob_dir=self.server_blob_dir)
        self._storage = self.openClientStorage()

        database = DB(self._storage)
        connection = database.open()
        root = connection.root()
        transaction.begin()
        b1 = Blob()
        with b1.open('w') as f:
            f.write(b'a' * 1024 * 8096)
        root['b1'] = b1
        b2 = Blob()
        with b2.open('w') as f:
            f.write(b'a' * 1024 * 8096)
        root['b2'] = b2
        transaction.commit()
```

To register you'll need
```diff
--- a/src/ZEO/tests/testConnection.py
+++ b/src/ZEO/tests/testConnection.py
@@ -56,6 +56,13 @@ class FileStorageConnectionTests(
     ):
     """FileStorage-specific connection tests."""

+
+class FileStorageBlobTests(
+    FileStorageConfig,
+    ConnectionTests.BlobTest,
+    ):
+    pass
+
 class FileStorageReconnectionTests(
     FileStorageConfig,
     ConnectionTests.ReconnectionTests,
@@ -102,6 +109,7 @@ test_classes = [FileStorageConnectionTests,
                 FileStorageReconnectionTests,
                 FileStorageInvqTests,
                 FileStorageTimeoutTests,
+                FileStorageBlobTests,
                 MappingStorageConnectionTests,
                 MappingStorageTimeoutTests,
                 ]
```

And to see the issue most clearly you can do this:
```diff
--- a/src/ZEO/asyncio/base.py
+++ b/src/ZEO/asyncio/base.py
@@ -78,6 +78,7 @@ class Protocol(asyncio.Protocol):
             # messages will be big to begin with.
             data = iter(data)
             for message in data:
+                print('write %s' % self.decode(message)[2])
                 writelines((pack(">I", len(message)), message))
                 if paused:
                     append(data)
@@ -143,9 +144,11 @@ class Protocol(asyncio.Protocol):
                       for method, args in it)

     def pause_writing(self):
+        print('pause 1')
         self.paused.append(1)

     def resume_writing(self):
+        print('pause 0')
         paused = self.paused
         del paused[:]
         output = self.output
```

Which will produce output like this, showing the invalid request interleaving:
```
write storeBlobStart
write storeBlobChunk
write storeBlobChunk
... (but not storeBlobEnd yet)
pause
resume
pause
resume
pause
write storeBlobStart
resume
```

**Comment by mamico** [comment]
We are experiencing, in the wild, many errors like these on the zeoserver side

```
2022-03-08T09:39:47 Bad async request, 'storeBlobStart'
Traceback (most recent call last):
  File ".../ZEO-5.2.2-py3.8.egg/ZEO/asyncio/server.py", line 103, in message_received
    result = getattr(self.zeo_storage, name)(*args)
  File ".../ZEO-5.2.2-py3.8.egg/ZEO/StorageServer.py", line 460, in storeBlobStart
    assert self.blob_tempfile is None
AssertionError
```
and related ClientDisconnected client-side errors

Using the test reported here, I saw the same behavior, so I assume we are experiencing issues that may be related to the bug explained here.

The big difference in the environment where we have the problem, compared to others where we don't, is that we are using not shared blobs. I suppose this increases the concurrency on blob write compared to the environment where blobs are shared with zeoclient, and consequently the issue depicted here.

@wosc seems to me your correction proposal [1] solves your test, although I can't guarantee it's the right solution. Why do you say it doesn't solve? 

\cc @jimfulton @jamadden @d-maurer any hints ? Thanks in advance

[1]
```
--- a/src/ZEO/asyncio/base.py
+++ b/src/ZEO/asyncio/base.py
@@ -76,8 +76,11 @@ class Protocol(asyncio.Protocol):
             # Note, don't worry about combining messages.  Iters
             # will be used with blobs, in which case, the individual
             # messages will be big to begin with.
-            data = iter(data)
-            for message in data:
+            if paused:
+                append(data)
+                return
+            for message in iter(data):
                 writelines((pack(">I", len(message)), message))
                 if paused:
                     append(data)

```

**Comment by d-maurer** [comment]
@mamico Would you check that #186 fixes the problems you have observed.

**Comment by d-maurer** [comment]
Mauro Amico wrote at 2022-3-11 08:31 -0800:
>> @mamico Would you check that #186 fixes the problems you have observed.
>
>Thanks. Tested in a staging environment, where the issue was easily replicable by sending two BLOBs on the same transaction. Now it works. I saw @wosc's solution in your proposal. My question is: is this the right solution?

@wosc found an obvious bug: `async_iter` has not garanteed a
correct message order (in the case of "pausing").
I created a test for this. His fix proposal resolves this bug
(and now my test succeeds). Thus, the fix improves things
(and `async_iter` will no longer pose problems).

@wosc wrote that his fix proposal has not solved all his problems.
Thus, there might be another problem not yet addressed.

**Comment by wosc** [comment]
Hi folks, thanks so much for taking a closer look at this! (And sorry for the delayed response, I've been out sick last week.) I'm afraid I don't remember the exact details anymore, it has been some years. ;) I _think_ that at the time I've wrote this down here, I had applied the proposed `if paused: return` snippet, but did not see the error go away, which left me pretty stumped. I'll gladly take another look at it now, maybe I'm just misremembering something (will take me a few days to get around to, though).

**Comment by wosc** [comment]
I now checked this again, and the fix works just fine for me, which means I cannot reconstruct what I had been seeing here originally, that caused me to write "my proposed bugfix does not fix the problem". So if someone could cut a release, that would be most excellent. Thanks!

**Comment by dataflake** [comment]
The fix is in the latest release, 5.3.0

**Comment by dataflake** [comment]
Oops, WILL BE in 5.3.0. My bad.IMHO it's ready to go.

**Comment by dataflake** [comment]
ZEO 5.3.0 is now released.

**Comment by d-maurer** [comment]
Mauro Amico wrote at 2022-3-10 01:24 -0800:
> ...
>Using the test reported here, I saw the same behavior, so I assume we are experiencing issues that may be related to the bug explained here.

I think you are right.

> ...
***@***.*** seems to me your correction proposal [1] solves your test, although I can't guarantee it's the right solution. Why do you say it doesn't solve?

I do not think that a solution has something to do with flow control
(and therefore `paused`). Instead, `startBlob` (in fact any method
causing messages to be transferred) should return only after
it has scheduled the transfer of all its messages; otherwise, a
different call may insert some of its messages into the
former message sequence and disrupt the order.

A source comment indicates that there is logic to combine
several smaller messages into a single packet and that
this logic is not necessary for blob block transfers.
I assume that the trial to avoid this logic is responsible
for the bug.
