### ISSUE TITLE
Travis build fails for Python 3.5 (BUILOUT_OPTIONS=extra=,uvloop)

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/ZEO#152]
https://travis-ci.org/zopefoundation/ZEO/builds/576843974?utm_medium=notification&utm_source=github_status

**Comment by jamadden** [comment]
The ZEO tests are a bit flaky (contain suspected race conditions or other timing sensitivites). A re-run of that particular job (Python 3.5 with uvloop) passed.

**Comment by jugmac00** [comment]
Uh, thank you. I refrained from working on some open issues because of the broken build - for no reason it seems :-?

Anyways, thank you for help!
