### ISSUE TITLE
"Bad request, 'vote'"

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/ZEO#156]
In a ZEO (5.2.1) logfile, I see several `Bad request, 'vote'` messages.

In all those cases, I see the following sequence of log entries:
 * the error information (including a traceback) for a failed conflict resolution
 * `Bad request, 'vote'` repeating the previous traceback, now associated with a `ConflictError`.
 * `no current transaction: tpc_abort()`

Apparently, ZEO turns a `ConflictError` into a `Bad request: 'vote'` (which in my view is wrong: it simply indicates that `vote` answers "no") and after that it gets confused by a `tpc_abort`.

**Comment by jugmac00** [comment]
Maybe this is related to https://github.com/zopefoundation/Products.SiteErrorLog/issues/21 ?

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2020-2-12 23:05 -0800:
>Maybe this is related to https://github.com/zopefoundation/Products.SiteErrorLog/issues/21 ?

No - a separate issue.

**Comment by ekulos** [comment]
Same issue in ZEO (5.1.1)

**Comment by djay** [comment]
We are seeing these errors however the date of the conflict is really old. 

```
2021-06-04T03:56:51 Bad request, 'vote'
Traceback (most recent call last):
  File "/buildout/eggs/ZEO-5.2.2-py3.8.egg/ZEO/asyncio/server.py", line 103, in message_received
    result = getattr(self.zeo_storage, name)(*args)
  File "/buildout/eggs/ZEO-5.2.2-py3.8.egg/ZEO/StorageServer.py", line 371, in vote
    return self.lock_manager.lock(self, self._vote)
  File "/buildout/eggs/ZEO-5.2.2-py3.8.egg/ZEO/StorageServer.py", line 1165, in lock
    result = func()
  File "/buildout/eggs/ZEO-5.2.2-py3.8.egg/ZEO/StorageServer.py", line 392, in _vote
    getattr(self, op)(*args)
  File "/buildout/eggs/ZEO-5.2.2-py3.8.egg/ZEO/StorageServer.py", line 526, in _store
    self.storage.store(oid, serial, data, '', self.transaction)
  File "/buildout/eggs/ZODB-5.6.0-py3.8.egg/ZODB/FileStorage/FileStorage.py", line 602, in store
    data = self.tryToResolveConflict(oid, committed_tid,
  File "/buildout/eggs/ZODB-5.6.0-py3.8.egg/ZODB/ConflictResolution.py", line 296, in tryToResolveConflict
    raise ConflictError(oid=oid, serials=(committedSerial, oldSerial),
ZODB.POSException.ConflictError: database conflict error (oid 0x01ea0a8d, class BTrees.OOBTree.OOBTree, serial this txn started with 0x03de22d424df5e55 2021-02-20 04:36:08.642000, serial currently committed 0x03e0822cdc0f23aa 2021-06-04 03:56:51.576360)
2021-06-04T03:56:51 (db:8100) no current transaction: tpc_abort()
```

We don't yet know if its related but we get lockups that last for hours and the server has to be reset. I'm guessing its related?

**Comment by d-maurer** [comment]
The "Bad request ..."  is a log message label to report any exception not in `unlogged_exception_types`. The message does not mean that the exception has been changed - it is still reported unchanged to the client.

In my view, the label should be changed to `[async]  `*method_name*` raised exception:`. This would more clearly indicate the informational intent.

The log message will disappear when we add `ConflictError` to `unlogged_exception_types`. In my view, we should do that because `ConflictError` is a normal response (at least for `vote`) and not an exception. I would delegate the decision whether to log `ConflictError` to the client (and its application).

**Comment by d-maurer** [comment]
The `no current transaction: tpc_abort()` log message comes from `StorageServer.ZEOStorage._check_tid`. The storage API allows `tpc_abort` to be called with an invalid transaction. The ZEO `vote` implementation makes use of this but `_check_tid` nevertheless logs a warning: `_check_tid` should get changed.
