### ISSUE TITLE
ZEO5 incredibly slow on Python 3[.6] compared to Python 2.7

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/ZEO#168]
@navytux reported in #166 a data corruption bug for ZEO 5 and provided a test script reproducing this problem. In #167, I implemented his script as a unittest (--> `ZEO.tests.testZEO.RaceConditionTests.test_open`). Running this test takes **much** more time on Python 3.6 than on Python 2.7:

Python 3.6:
zope-testrunner --test-path src -vvv -t test_open
 test_open (ZEO.tests.testZEO.RaceConditionTests) (227.710 s)

Python 2.7
zope-testrunner --test-path src -vvv -t test_open
 test_open (ZEO.tests.testZEO.RaceConditionTests) (7.332 s)

This means that the test is almost 30 times slower on Python 3.6 than on Python 2.7.

**Comment by navytux** [comment]
@d-maurer, thanks for heads up. That probably explains why original problem from https://github.com/zopefoundation/ZEO/issues/166 reproduces failure only on Python2.

**Comment by d-maurer** [comment]
Kirill Smelkov wrote at 2021-4-13 02:02 -0700:
***@***.***, thanks for heads up. That probably explains why original problem from https://github.com/zopefoundation/ZEO/issues/166 reproduces failure only on Python2.

The cause might be a local peculiarity:
the test suite for #167 has run on Travis
("https://travis-ci.com/github/zopefoundation/ZEO/jobs/498094811" (2.7)
and ("https://travis-ci.com/github/zopefoundation/ZEO/jobs/498094814" (3.6))
without significant runtime differences.
Interestingly, `test_open` failed there for Python 3 as well.
Thus like Python 2, Python 3 is affected by #166.

Note: `test_open` fails because a too old ZODB version is used.

**Comment by d-maurer** [comment]
The test mentioned in this report has run on Travis without significant runtime differences between Python 3.6 and Python 2.7. Something seems to be wrong with my local Python 3.6 installation.

**Comment by navytux** [comment]
@d-maurer, I've checked with python2.7 and python3.9 and I confirm your findings: on my machine with N=1E4  it takes ~36s on py3 and ~40s on py2 for `zopenrace-zeo.py` to run.

**Comment by d-maurer** [comment]
> This means that the test is almost 30 times slower on Python 3.6 than on Python 2.7.

Profiling revealed that the time is essentially spent in `send` and `recv` of socket objects. That should not happen as the sockets are in nonblocking mode (verified).

A similar slowdown by a factor of 30 was reported in "https://bugs.python.org/issue27456". There, the slowdown was observed comparing MAC OS to some Linux versions. The solution has been to set the socket option `TCP_NODELAY`. Since Python 3.6, this is automatically set by `asyncio` (verified). Nevertheless, the current observation might have a similar cause and may depend on the OS type and version.

**Comment by d-maurer** [comment]
The problem is (mostly) understood: The runtime of the test heavily depends on thread switch frequency. Python 2 typically switches threads every 100 interpreter instructions, Python 3 every 5 milliseconds; thus, Python 2 typically switches threads with much higher frequency which explains the runtime differences.
The dependence on thread switch frequency hints towards GIL/CPU congestion. Indeed, the test's checker thread is almost unbraked and ready to consume all available CPU cycles.
With proper slowdowns in the checker and mutator threads, the runtime difference between Python 2 and Python 3 disappears.
