### ISSUE TITLE
tests hard depend on deprecated mock

### ISSUE THREAD

**Issue by pgajdos** [zopefoundation/ZEO#184]
Could you please consider to use something like
```
-        import mock
+        try:
+           from unittest import mock as mock
+        except ImportError:
+           import mock
```
in the code?

**Comment by pgajdos** [comment]
fx.
https://build.opensuse.org/package/view_file/home:pgajdos:python/python-ZEO/python-ZEO-no-mock.patch

**Comment by d-maurer** [comment]
pgajdos wrote at 2021-9-24 02:29 -0700:
>Could you please consider to use something like
>```
>-        import mock
>+        try:
>+           from unittest import mock as mock
>+        except ImportError:
>+           import mock
>```
>in the code?

`unittest.mock` is not (yet?) deprecated in the latest
Python final release (3.9.7).

Therefore, I do not see a need to change anything for the moment.



--
Dieter

**Comment by ale-rt** [comment]
I think the idea was to remove mock, which is now available in the unittest module.
Also the setup.py needs to be changed:
https://github.com/zopefoundation/ZEO/blob/0a8d23166b7804d56a4c3f381ef316e3088fbb67/setup.py#L37
It should be `"mock;python_version<'3'"`

**Comment by d-maurer** [comment]
Dieter Maurer wrote at 2021-9-24 11:35 +0200:
>pgajdos wrote at 2021-9-24 02:29 -0700:
>>Could you please consider to use something like
>>```
>>-        import mock
>>+        try:
>>+           from unittest import mock as mock
>>+        except ImportError:
>>+           import mock
>>```
>>in the code?
>
>`unittest.mock` is not (yet?) deprecated in the latest
>Python final release (3.9.7).
>
>Therefore, I do not see a need to change anything for the moment.

Maybe, I did not understand your intention: you want that
the tests use `unittest.mock` rather than `mock`?
In this case, I agree with you.

`unittest.mock` is available for all Python 3 versions supported by ZEO.
It is not available for Python 2.7.
Thus, the external distribution "mock" is required only for Python 2.



--
Dieter

**Comment by icemac** [comment]
We could defer this change to a point in time after dropping Python 2 support. This would create a much smaller diff and could be achieved using [pyupgrade's](https://pypi.org/project/pyupgrade/) rewrite mock imports feature.

**Comment by pgajdos** [comment]
Ah yes, thank you! 
(Not sure whether I should close the bug then.)

**Comment by dataflake** [comment]
Yes, please close the issue.
