### ISSUE TITLE
Remove possibly unused MTAcceptor feature

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/ZEO#188]
I have a feeling that this package is carrying a lot of baggage in terms of features that are covered by tests but I have never heard anyone use them.

When setting the environment variable `ZEO_MTACCEPTOR` to a true value enables a feature whereby the ZEO storage server runs each connection in its own thread. The comment at the top of the module `asyncio/mtacceptor.py` says:

``
Testing serveral years ago
suggsted that this was a win, but ZODB shootout and another
lower-level tests suggest otherwise.  It's really unclear, which is
why we're keeping this around for now.
``

The code has been retained for years and years and updated where needed. I wonder if it's used anywhere instead of being nothing but a maintenance burden.

**Comment by icemac** [comment]
I do not know this feature. I believe gocept is not using it in any of our projects. So from my side 👍 to remove it.

**Comment by icemac** [comment]
@jamadden and @jimfulton are the ones who GitHub lists as contributors to `asyncio/mtacceptor.py` so your voice should have more weight than my unimportant personal opinion.

**Comment by jamadden** [comment]
My group never used that feature. I wouldn't be sorry to see it go if it simplifies things.

**Comment by d-maurer** [comment]
In normal mode, the ZEO server is essentially single threaded and performs a single operation at a time; only a few especially long running operations (`pack`, `UndoInfo`, `UndoLog') are executed in their own threads.

In `MTAcceptor` mode, each connection gets its own thread; the ZEO server becomes multi threaded (but there is still at most one active commit per storage). Theoretically, this could speed up loads when the server is used from different clients -- as its requests are IO bound and can in principle be served concurrently.

If we drop `MTAcceptor` quite a few things could be simplified: we would have a single `asyncio` loop used (apart from the single exception `MTDelay`) by a single thread  - we would no longer need "threadsafe" call variants and we could remove the lock from the `LockManager`.

**Comment by dataflake** [comment]
Simplification is definitely a worthy goal. Anything that makes this package more maintainable is welcome.
