### ISSUE TITLE
Race test `check_race_external_invalidate_vs_disconnect` fails on macOS

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/ZEO#222]
The race test `check_race_external_invalidate_vs_disconnect`, which is defined in the ZODB package, fails reliably on macOS regardless of the backing storage used by the test. The failure is `OSError: [Errno 24] Too many open files`.

The test definition in the module `ZODB/tests/racetests.py` sets a hardcoded number of 64 workers. That is too much for macOS. Manual testing has shown that dialing it down to 43 workers will make the tests run successfully.

The test itself is "re-used" by ZEO. Running the ZODB tests by themselves doesn't show the issue, 64 workers is fine in that case. I wonder if there's some elegant way of moving that worker limit setting somewhere else so it can be changed temporarily from within the ZEO tests if e.g. `sys.platform == 'darwin'`.

**Comment by dataflake** [comment]
(Assigning @navytux because he authored the racetests module)

**Comment by navytux** [comment]
@dataflake, thanks for the report. Could you please show what is your `ulimit -a` there? And if there is a way to raise `ulimit -n` ? ZEO fails here probably because the limit for file descriptors is relatively low and each ClientStorage uses at least one file descriptor for socket connecting to the server.

**Comment by dataflake** [comment]
You're right, increasing that limit manually helps. See #223 for an attempt to do that during the tests.

**Comment by navytux** [comment]
Thanks.
