### ISSUE TITLE
Request release for 5.x branch on PyPI

### ISSUE THREAD

**Issue by rafaelbco** [zopefoundation/ZEO#229]
Could you please make a new release for the 5.x branch on PyPI?

I'm doing some load tests for my Plone 5.2 application and the latest version from the 5.x branch seems to be working OK and giving slightly fewer conflict errors.

The unreleased fix for #226 mentioned in the changelog seems relevant.

Thanks!

**Comment by dataflake** [comment]
I made the release just now.

GH has removed Python 2.7 now (see https://github.com/actions/setup-python/issues/672) so the Python 2.7 tests are now broken. I tried a couple workarounds but they did not work. If anyone feels strongly about these automates tests on Python 2.7 I encourage you to step in. I'm not spending time on any Python 2.7 issue anymore.

**Comment by navytux** [comment]
Jens, thanks for making the release. And I see your position about Python 2.7 .
