### ISSUE TITLE
Release version 6.0

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZEO#238]
After #237 is merged, it would be a good time to cut a 6.0 release.

Can someone cut a release or add me (`icemac`) to PyPI so I can do it?

Cc-ing current PyPI maintainers:

@jimfulton @tseaver @dataflake

**Comment by dataflake** [comment]
Unfortunately I don't have the privilege level to add users.

**Comment by tseaver** [comment]
I've made @dataflake an `Owner` on PyPI ZEO, and invitd @icemac as an `Owner` as well.
