### ISSUE TITLE
AttributeError: 'FullGenericTests' object has no attribute 'getConfig'

### ISSUE THREAD

**Issue by MeggyCal** [zopefoundation/ZEO#240]
### What I did:

I tried to package ZEO 6.0.0 for openSUSE including running tests. There was an error:

```
[   21s] ERROR: testPackUndoLog (ZEO.tests.testZEO.FullGenericTests)
[   21s] ----------------------------------------------------------------------
[   21s] Traceback (most recent call last):
[   21s]   File "/home/abuild/rpmbuild/BUILD/ZEO-6.0.0/src/ZEO/tests/testZEO.py", line 274, in setUp
[   21s]     self.getConfig(), self.getZEOConfig(), debug=self.server_debug)
[   21s] AttributeError: 'FullGenericTests' object has no attribute 'getConfig'
```

It looks like to me that someone got lost in multiple inheritance and deleted a piece of code which had to stay. But the `FullGenericTests` class inherits from so many classes that I didn't investigate further, it would be a mess.

### What version of Python and Zope/Addons I am using:

Fails on Python 3.9 +, `zope.testing-5.0.1` and `zope.interface-6.2`.

**Comment by MeggyCal** [comment]
oh, yes, and `ZODB-5.8.1`, but it was supposed to pass on this, wasn't it?

**Comment by d-maurer** [comment]
`ZEO==6.0.0` is almost identical to the current `ZEO@master`. I have checked (--> "https://github.com/zopefoundation/ZEO/actions/runs/8315256522") that the latest `master` tests have been successful. Thus, the tests succeed (with proper dependencies). I assume that the tests mentioned above use the latest released `ZODB` version.

**Comment by perrinjerome** [comment]
I see this error when running `python3.9 -m unitest` from `src/ZEO` folder, is it by chance what you tried ? If yes, this is not a supported way of running tests (see github actions or tox.ini for supported ways)

**Comment by MeggyCal** [comment]
> I see this error when running `python3.9 -m unitest` from `src/ZEO` folder, is it by chance what you tried ? If yes, this is not a supported way of running tests (see github actions or tox.ini for supported ways)

Yes, this is what I was doing :) thank you for the links. Closing this issue.
