### ISSUE TITLE
LockError errors when using blob-cache-size

### ISSUE THREAD

**Issue by alecghica** [zopefoundation/ZEO#3]
Hi,

I am using a ZEO client having this configuration:

```
shared-blob-dir off
cache-size 350MB
blob-cache-size 70000000
blob-cache-size-check 10
```

The `blob-cache-size` works fine and the limit is pretty well kept but the Zope/Plone console is full of the bellow errors. The error happens when a previously deleted blob file from blob cache is accessed:

```
ERROR zc.lockfile Error locking file /var/work/zodbblobcache/check_size.lock; pid=UNKNOWN
Traceback (most recent call last):
  File "/var/work/myPlone/eggs/zc.lockfile-1.0.0-py2.6.egg/zc/lockfile/__init__.py", line 76, in __init__
    _lock_file(fp)
  File "/var/work/myPlone/eggs/zc.lockfile-1.0.0-py2.6.egg/zc/lockfile/__init__.py", line 59, in _lock_file
    raise LockError("Couldn't lock %r" % file.name)
LockError: Couldn't lock '/var/work/zodbblobcache/check_size.lock'
```

The Zope/Plone UI is not reporting any errors and files are accessible but the logs are full of this `LockError` errors. Why is this happening and how it can be avoided? Is this an INFO message wrongly marked as an ERROR?

---

Thx,
Alec

**Comment by hvelarde** [comment]
is this still an issue?

**Comment by jimfulton** [comment]
Yes, I think so. Wow, this was 4 years ago. I don't really remember this conversation. :)

**Comment by kingel** [comment]
Any pointers on this? I see two related (old) PR's in https://github.com/zopefoundation/zc.lockfile/pulls to make it less noisy, but I guess it is better to look for the reason for this errors.

**Comment by jimfulton** [comment]
See https://github.com/zopefoundation/zc.lockfile/pull/3.

I plan to merge that, which will stop the noise. :)

**Comment by dataflake** [comment]
Closing issue, the PR Jim referred to was merged and a new version of zc.lockfile released in 2018.
