### ISSUE TITLE
Can't connect to ZEO server on  Windows

### ISSUE THREAD

**Issue by gouthambs** [zopefoundation/ZEO#8]
This is a duplicate of the issue found here:
https://bugs.launchpad.net/zodb/+bug/1004513

The solution provided by Lubomir Kostov (lkostov) works, and I have tried the fix as well. I can resubmit a PR if needed.

**Comment by janssen** [comment]
Just a vote for an included Windows service.  It's really the way to do it on Windows, and Python makes it easy (or, rather, PyWin32 makes it easy).

**Comment by heavelock** [comment]
This bug is still affecting ZEO on localhost on Windows. I'm using Python 3.5.0, ZEO 4.2.0b1 and Windows 10. 

I've tried to use bugfix proposed by lkostov on Launchpad(https://bugs.launchpad.net/zodb/+bug/1004513/comments/3), but it throws a bunch of errors. 

Are testers still needed?

**Comment by tseaver** [comment]
We're working on adding [appveyor support](http://www.appveyor.com/) to other ZF packages.  We need to improve the story about who "owns" the integration:  right now, @mgedmin has the keys, but he rightfully doesn't want to keep them.

**Comment by jimfulton** [comment]
Great news re appveyor!!! I hadn't noticed that before.
