### ISSUE TITLE
runzeo problem with opening storages obscured by cleanup code

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/ZEO#81]
In:

    def main(self):
        self.setup_default_logging()
        self.check_socket()
        self.clear_socket()
        self.make_pidfile()
        try:
            self.open_storages()
            self.setup_signals()
            self.create_server()
            self.loop_forever()
        finally:
            self.server.close()
            self.clear_socket()
            self.remove_pidfile()

If there's a failure in or before create_server, the first statement in the finally block will fail, hiding the original error.

**Comment by jamadden** [comment]
I think this is the same as #19

**Comment by jimfulton** [comment]
Thanks for pointing that out.
