### ISSUE TITLE
ZConfig 3.2.0 leads to stale socket files on Python 2

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ZEO#90]
[A change](https://github.com/zopefoundation/ZConfig/commit/010cb2b2d4d2cdc8cd327f9f46a987024cac5b67#diff-bd559d1f48a7d2df54fca55965db90b2R223) in ZConfig 3.2.0 leads to socket binding addresses being text on both Python2 and Python3.

This breaks runzeo.py's [`ZEOServer.clear_socket` method](https://github.com/zopefoundation/ZEO/blob/master/src/ZEO/runzeo.py#L196) (on Python 2) which only removes the socket file if it is the type of a string literal:
```python

def clear_socket(self):
  if isinstance(self.options.address, type("")):
     try:
        os.unlink(...)
```

Under Python 2, the string literal is a `bytes` object, not a text object.

Now, this wasn't a documented ZConfig change and it wasn't even exactly intended (it was the result of consistency improvements between the behaviour of Python 2 and Python 3, plus bug fixes). Still, because this project already has a dependency on `six`, it seems to make sense to use `six.string_types` there instead of `type("")`, which would solve the issue.

**Comment by tseaver** [comment]
WFM

**Comment by jamadden** [comment]
I should add that this is a second-hand report from some colleagues of mine. I haven't tried to write a test case or verify yet.

**Comment by jzuech3** [comment]
A monkey patch doing what you suggested (check for `six.string_types` instead of `type("")`) works for me.

**Comment by jamadden** [comment]
I think @tseaver was saying that the code *as-is* works for him, he doesn't see stale socket files using ZEO and ZConfig 3.2.0 under Python 2, so no patch appears to be needed. Maybe there's some other element? (Again, I haven't tried to create a reproducible test case yet myself.)

**Comment by tseaver** [comment]
Sorry, my "WFM" was meant to say, "that patch [would] work for me."

**Comment by jamadden** [comment]
Thanks for the clarification!
